### ISSUE TITLE
Permission error

### ISSUE THREAD

**Issue by OkGamez313** [hearmeneigh/e621-rising-configs#2]
Generating previewTraceback (most recent call last):
  File "/home/okgamez/.local/bin/dr-preview", line 8, in <module>
    sys.exit(main())
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 184, in main
    save_results_to_html(args.output, result['includes'], tpl, args.selector, 'includes')
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 94, in save_results_to_html
    os.makedirs(base_path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
⠋ Verifying selector tagsTag name "artist:nib-roc" not found in the database; skipping tag from the filter: ./select/tier-1/tier-1.yaml
✔ Selector tags verified
⠆ Generating previewTraceback (most recent call last):
  File "/home/okgamez/.local/bin/dr-preview", line 8, in <module>
    sys.exit(main())
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 172, in main
    save_results_to_html(args.output, result, tpl, args.selector, 'aggregated')
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 94, in save_results_to_html
    os.makedirs(base_path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
⠋ Verifying selector tagsTag name "artist:nib-roc" not found in the database; skipping tag from the filter: ./select/tier-2/tier-2.yaml
✔ Selector tags verified
⠆ Generating previewTraceback (most recent call last):
  File "/home/okgamez/.local/bin/dr-preview", line 8, in <module>
    sys.exit(main())
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 172, in main
    save_results_to_html(args.output, result, tpl, args.selector, 'aggregated')
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 94, in save_results_to_html
    os.makedirs(base_path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
✔ Selector tags verified
⠆ Generating previewTraceback (most recent call last):
  File "/home/okgamez/.local/bin/dr-preview", line 8, in <module>
    sys.exit(main())
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 172, in main
    save_results_to_html(args.output, result, tpl, args.selector, 'aggregated')
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 94, in save_results_to_html
    os.makedirs(base_path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
✔ Selector tags verified
⠆ Generating previewTraceback (most recent call last):
  File "/home/okgamez/.local/bin/dr-preview", line 8, in <module>
    sys.exit(main())
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 172, in main
    save_results_to_html(args.output, result, tpl, args.selector, 'aggregated')
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 94, in save_results_to_html
    os.makedirs(base_path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
✔ Selector tags verified
⠆ Generating previewTraceback (most recent call last):
  File "/home/okgamez/.local/bin/dr-preview", line 8, in <module>
    sys.exit(main())
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 172, in main
    save_results_to_html(args.output, result, tpl, args.selector, 'aggregated')
  File "/home/okgamez/.local/lib/python3.10/site-packages/database/dr_preview.py", line 94, in save_results_to_html
    os.makedirs(base_path, exist_ok=True)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/workspace'
usage: Gap [-h] -s FILE -o FILE -c CATEGORY [-l COUNT] [-i FORMAT] [-f FORMAT] [-t FILE]
Gap: error: argument -c/--category: invalid choice: 'artists' (choose from 'general', 'species', 'character', 'artist', 'copyright', 'meta', 'lore', 'symbol', 'aspect_ratio', 'rating', 'score', 'favorites', 'comments', 'views', 'description', 'rising', 'invalid')

I get this error after testing the selectors on the prebuilt docker image. I have no idea what im doing

**Comment by hearmeneigh** [comment]
It looks like that `/workspace` directory is not writable. You may need to do something like `sudo mkdir /workspace && sudo chown okgamez:okgamez /workspace` to get it to work.

Alternatively just point to something else than `/workspace` that is already writable, such as `/home/okgamez/something/or/other`

**Comment by OkGamez313** [comment]
now there's another error
```
⠰ Generating preview (this will take a while)Traceback (most recent call last):
  File "/home/jayden/.local/bin/dr-gap", line 8, in <module>
    sys.exit(main())
  File "/home/jayden/.local/lib/python3.10/site-packages/database/dr_gap.py", line 169, in main
    result = [sample_posts(tag['preferred_name'], args.limit, db, args.image_format) for tag in category_tags if does_not_match_selectors(tag['preferred_name'], selectors)]
  File "/home/jayden/.local/lib/python3.10/site-packages/database/dr_gap.py", line 169, in <listcomp>
    result = [sample_posts(tag['preferred_name'], args.limit, db, args.image_format) for tag in category_tags if does_not_match_selectors(tag['preferred_name'], selectors)]
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/cursor.py", line 1251, in next
    if len(self.__data) or self._refresh():
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/cursor.py", line 1191, in _refresh
    self.__send_message(g)
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/cursor.py", line 1055, in __send_message
    response = client._run_operation(
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
⠠ Generating preview (this will take a while)return func(self, *args, **kwargs)
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1341, in _run_operation
    return self._retryable_read(
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/_csot.py", line 106, in csot_wrapper
    return func(self, *args, **kwargs)
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1465, in _retryable_read
    return func(session, server, sock_info, read_pref)
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/mongo_client.py", line 1337, in _cmd
    return server.run_operation(
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/helpers.py", line 279, in inner
    return func(*args, **kwargs)
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/server.py", line 135, in run_operation
    _check_command_response(first, sock_info.max_wire_version)
  File "/home/jayden/.local/lib/python3.10/site-packages/pymongo/helpers.py", line 192, in _check_command_response
    raise CursorNotFound(errmsg, code, response, max_wire_version)
pymongo.errors.CursorNotFound: cursor id 851527346825382217 not found, full error: {'ok': 0.0, 'errmsg': 'cursor id 851527346825382217 not found', 'code': 43, 'codeName': 'CursorNotFound'}
```
